=========================== Define thread - by implementing runnable Interface =================
Runnable interface present in java.lang package and only one method run();
// Defining a Thread
class myRunnable implements Runnable {
	public void run() {
		for(int i = 0; i < 10; i++) {
			System.out.println("Child Thread");
		}
	}
}

class ThreadDemo {
	public static void main(String[] args) {
		myRunnable r = new myRunnable();
		Thread t = new Thread(r);
		t.start();
		for(int i = 0; i < 10; i++) {
			System.out.println("Main Thread");
		}
	}
}

Mixed output

Case study :
myRunnable r = new myRunnable();
Thread t1 = new Thread();
Thread t1 = new Thread(r);

Case 1: t1.start(); - a new thread is created and responsible for the execution of thread class run(), which has empty implementation.
Case 2: t1.run(); - no new thread is created and thread class run() will be executed just like a normal method call.
Case 3: t2.start(); - a new thread is created and responsible for execution of myRunnable class run().
Case 4: t2.run(); - a new thread won't be created and myRunnable run() will be executed just like a normal method call.
Case 5: r.start(); - compiletime error - CE: cannot find symbol, symbol:method start() location: class myRunnable.
Case 6: r.run(); - no new thread created and myRunnable run() will be executed like normal method call.

========================= Which approach is best to define a thread ? ================================
In Java, there are primarily two ways to define a thread:

1. Extending Thread class
2. Implementing Runnable interface

Among these, implementing Runnable is generally the recommended approach.

class MyThread extends Thread {
    public void run() {
        System.out.println("Child Thread");
    }
}

public class Demo {
    public static void main(String[] args) {
        MyThread t = new MyThread();
        t.start();
    }
}

Java supports only single inheritance.
class MyThread extends Thread, Employee { } // ❌ Not possible

Approach 2:
class MyTask implements Runnable {
    public void run() {
        System.out.println("Child Thread");
    }
}

public class Demo {
    public static void main(String[] args) {
        MyTask task = new MyTask();
        Thread t = new Thread(task);
        t.start();
    }
}

1. Supports Inheritance:
class Employee {
}

class MyTask extends Employee implements Runnable {
    public void run() {
        System.out.println("Child Thread");
    }
}

2. Better Object-Oriented Design
It separates:
Task → Runnable
Thread execution mechanism → Thread

3. Same Task Can Be Executed by Multiple Threads
MyTask task = new MyTask();

Thread t1 = new Thread(task);
Thread t2 = new Thread(task);

t1.start();
t2.start();

4. Works Well with Modern Concurrency APIs
ExecutorService executor = Executors.newFixedThreadPool(5);

executor.submit(new MyTask());

Modern approach:
In production code, we usually use lambda expressions + ExecutorService.

ExecutorService executor = Executors.newFixedThreadPool(2);

executor.submit(() -> {
    System.out.println("Executed by " + Thread.currentThread().getName());
});

executor.shutdown();

This approach provides:

Thread pooling
Better resource management
Scalability
Easier exception handling
========================= Which approach is best to define a thread ? ================================

========================= Thread Class Constructors ================================
Thread()
Thread(String name)
Thread(Runnable target)
Thread(Runnable target, String name)
Thread(ThreadGroup group, String name)
Thread(ThreadGroup group, Runnable target)
Thread(ThreadGroup group, Runnable target, String name)
Thread(ThreadGroup group, Runnable target, String name, long stackSize)

========================= Thread Class Constructors ================================
class myThread extends Thread {
	public void run() {
		System.out.println("Child Thread");
	}
}
class ThreadDemo {
	public static void main(String[] args) {
		myThread t = new myThread();
		Thread t1 = new Thread(t);
		t1.start();
		System.out.println("Main Thread");
	}
}

=============== Getting & Setting name of a Thread =============================
Every thread in Java has some name it may by default name generated by JVM or customized name provided by programmer.We can get & set name of a thread by using -

public final String getName()
public final void setName(String name)

class MyThread extends Thread {
}
class Test {
	public static void main(String[] args) {
		System.out.println(Thread.currentThread().getName());
		MyThread t = new MyThread();
		System.out.println(t.getName());
		Thread.currentThread().setName("NewThreadName");
		System.out.println(Thread.currentThread().getName());
	}
}

Output:
main
Thread-0
NewThreadName

We can get current executing thread object Thread.currentThread()

class MyThread extends Thread {
	public void run() {
		System.out.println("run method executed by Thread:" + Thread.currentThread().getName());
	}
}
class Test {
	public static void main(String[] args) {
		MyThread t = new MyThread();
		t.start();
		System.out.println("Main method executed by Thread:" + Thread.currentThread().getName());
	}
}

Output:
run method executed by Thread: main
Main method executed by Thread: Thread-0