===================================== Constructor ===============================
A Constructor is a special member of a class that is executed automatically when an object is created.Initialize the object's state (instance variables).
Once we create an object compulsory we need to initialization then only the object is in a position to respond properly.
Whenever we are creating an object some piece of code will be executed to perform initialization of the object this piece of code is constructor.
Hence the main purpose of the constructor is initialization of an object.
The main purpose os to initialization of an object but not to create an object.

class Student {
	String name;
	int rollno;
	
	Student(String name, int rollno) {
		this.name = name;
		this.rollno = rollno;
	}
	
	public static void main(String[] args) {
		Student s1 = new Student("Jonny",1);
		Student s2 = new Student("Mark",2);
	}
}
===================================== Constructor ===============================
============================Difference between constructor and instance block ===========================================

The main purpose of constructor is to initialization of an object. But other then initialization if we want to perform any activity for every object creation then we should go for "instance block"(Updating one entry in the database for every object creation or incrementing count value for every object creation etc.)

Both constructor and instance block have their own different purposes and replacing one concept with another concept may not work always.
Both constructor & instance block will be executed for every object creation but instance block 1st followed by constructor.

class Test {
	static int count = 0;
	{
		count++;
	}
	Test() { }
	Test(int i){ }
	Test(double d){ }
	
	public static void main(String[] args) {
		Test t1 = new Test();
		Test t2 = new Test(10);
		Test t3 = new Test(10.5);
		
		System.out.println("The no. of objects created:" + count);
	}
}

Rules of writing constructor -
1. Name of the class and name of the constructor must be matched.
2. No return type
3. Applicable modifiers for constructor are - public, private, protected & default otherwise compiletime error : modifier static not allowed here.

Default Constructor :
1. Compiler is responsible to generate default constructor but not JVM.
2. If we are not writing any constructor then only compiler will generate default constructor i.e., if we are writing atleast one constructor then compiler won't generate default constructor, hence every class in Java can contain constructor it may be default constructor generated by compiler or customized constructor explicitly provided by programmer but not both simultaneously.
		
============================Difference between constructor and instance block ===========================================		